const VORONOI_NUMBER_CONSTANT = {
  SEED: 0.42,
  TARGET_POINT: 3650,
  NUMBER_OF_LLOYD_ATTEMPTS: 2,
} as const;

const VORONOI_COLOR_CONSTANT = {
  WHITE: "#FFFFFF",
  GRAY: "#EEEEEE",
};

export { VORONOI_COLOR_CONSTANT, VORONOI_NUMBER_CONSTANT };
