const VORONOI_NUMBER_CONSTANT = {
  SEED: 0.42,
  PERIOD: 365,
  PERIOD_POINT_SCALE: 5,
  NUMBER_OF_LLOYD_ATTEMPTS: 3,
} as const;

const VORONOI_COLOR_CONSTANT = {
  WHITE: "#FFFFFF",
  GRAY: "#EEEEEE",
};

export { VORONOI_COLOR_CONSTANT, VORONOI_NUMBER_CONSTANT };
